#!/usr/bin/env python3
import os
import sys
from src.repository import Repository
from commands.add import AddCommand
from commands.init import InitCommand
from commands.rm import RmCommand
from commands.commit import CommitCommand
from commands.status import StatusCommand
from commands.log import LogCommand

class CLI:
    def __init__(self):
        self.repo = Repository(os.getcwd())
        self.commands = {
            'init': InitCommand,
            'add': AddCommand,
            'rm': RmCommand,
            'commit': CommitCommand,
            'status': StatusCommand,
            'log': LogCommand,
        }

    def run(self):
        if len(sys.argv) < 2:
            self._print_usage()
            return

        command_name = sys.argv[1]
        command_args = sys.argv[2:]

        if command_name in self.commands:
            CommandClass = self.commands[command_name]
            command_instance = CommandClass(self.repo, command_args)
            command_instance.run()
        else:
            sys.stderr.write(f"Error: Unknown command '{command_name}'\n")
            self._print_usage()

    def _print_usage(self):
        sys.stderr.write("Usage: bit <command> [<args>]\n")
        sys.stderr.write("Available commands:\n")
        for name in self.commands:
             sys.stderr.write(f"  {name}\n")

if __name__ == "__main__":
    CLI().run()